package com.mikusz3.mikuszplanner.ui.theme

import androidx.compose.ui.graphics.Color

// ── Windows 9x ──────────────────────────────────────────────────────────────
val Win9x_Bg          = Color(0xFFC0C0C0)
val Win9x_Light       = Color(0xFFE0E0E0)
val Win9x_Dark        = Color(0xFF808080)
val Win9x_Darkest     = Color(0xFF404040)
val Win9x_White       = Color(0xFFFFFFFF)
val Win9x_Black       = Color(0xFF000000)
val Win9x_Navy        = Color(0xFF000080)
val Win9x_Teal        = Color(0xFF008080)
val Win9x_TitleStart  = Color(0xFF000080)
val Win9x_TitleEnd    = Color(0xFF1084D0)
val Win9x_ButtonFace  = Color(0xFFC0C0C0)
val Win9x_Highlight   = Color(0xFF000080)
val Win9x_HighText    = Color(0xFFFFFFFF)

// ── Windows XP Luna ─────────────────────────────────────────────────────────
val XP_TitleStart     = Color(0xFF0A52A3)
val XP_TitleEnd       = Color(0xFF3A9FE8)
val XP_BgPane         = Color(0xFFECE9D8)
val XP_BtnFace        = Color(0xFFECE9D8)
val XP_BtnBlue        = Color(0xFF316AC5)
val XP_BtnBlueHover   = Color(0xFF4D85D9)
val XP_StartGreen     = Color(0xFF1E7A1E)
val XP_Text           = Color(0xFF000000)
val XP_BlueText       = Color(0xFF0057A8)
val XP_SelectedBg     = Color(0xFF316AC5)
val XP_SelectedText   = Color(0xFFFFFFFF)
val XP_TaskbarBg      = Color(0xFF245EDC)
val XP_GreenBar       = Color(0xFF3DCC3D)
val XP_SilverBorder   = Color(0xFF919B9C)
val XP_FormBg         = Color(0xFFFFFFFF)

// ── Frutiger Aero ────────────────────────────────────────────────────────────
val Aero_Sky          = Color(0xFF87CEEB)
val Aero_DeepBlue     = Color(0xFF1B6CA8)
val Aero_LightBlue    = Color(0xFFBBDEFB)
val Aero_Aqua         = Color(0xFF00BFFF)
val Aero_Green        = Color(0xFF4CAF50)
val Aero_LightGreen   = Color(0xFFA5D6A7)
val Aero_White        = Color(0xFFFFFFFF)
val Aero_Bg           = Color(0xFFE1F3FB)
val Aero_GlassWhite   = Color(0xB0FFFFFF)
val Aero_GlassDark    = Color(0x30000080)
val Aero_GlossTop     = Color(0x70FFFFFF)
val Aero_TextDark     = Color(0xFF0D3B66)
val Aero_Gradient1    = Color(0xFF1565C0)
val Aero_Gradient2    = Color(0xFF42A5F5)

// ── Notebook Cards ───────────────────────────────────────────────────────────
val NB_Paper          = Color(0xFFFFFDE7)
val NB_LineBlue       = Color(0xFFBBDEFB)
val NB_RedMargin      = Color(0xFFEF9A9A)
val NB_Ink            = Color(0xFF1A237E)
val NB_Cover          = Color(0xFF1565C0)
val NB_Ring           = Color(0xFF9E9E9E)
val NB_Pink           = Color(0xFFFFCDD2)
val NB_Yellow         = Color(0xFFFFF9C4)
val NB_Blue           = Color(0xFFBBDEFB)
val NB_Green          = Color(0xFFC8E6C9)
val NB_Purple         = Color(0xFFE1BEE7)
val NB_Pencil         = Color(0xFFFFC107)
val NB_StickyYellow   = Color(0xFFFFF176)
val NB_StickyPink     = Color(0xFFF48FB1)
val NB_StickyBlue     = Color(0xFF81D4FA)

// ── iPod YouTube (200X) ──────────────────────────────────────────────────────
val iPod_Bg           = Color(0xFF0F0F0F)
val iPod_Surface      = Color(0xFF1A1A1A)
val iPod_Card         = Color(0xFF212121)
val iPod_CardHover    = Color(0xFF2C2C2C)
val iPod_Red          = Color(0xFFFF0000)
val iPod_DarkRed      = Color(0xFFCC0000)
val iPod_White        = Color(0xFFFFFFFF)
val iPod_LightGray    = Color(0xFFAAAAAA)
val iPod_MidGray      = Color(0xFF666666)
val iPod_Border       = Color(0xFF333333)
val iPod_GlossWhite   = Color(0x25FFFFFF)
val iPod_Selected     = Color(0xFF3A3A3A)
val iPod_Thumbnail    = Color(0xFF1E1E1E)
